CREATE TABLE "notes" (
	"n_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
	"modified" TIMESTAMP NOT NULL,
	"content" TEXT,
	"name" TEXT NOT NULL,
	"folder_id" INTEGER 
-- cascade delete
	CONSTRAINT "notes_pk" PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "folders" (
	"f_id" INTEGER NOT NULL,
	"name" INTEGER NOT NULL,
	"modified" TIME NOT NULL,
	CONSTRAINT "folders_pk" PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



ALTER TABLE "notes" ADD CONSTRAINT "notes_fk0" FOREIGN KEY ("folder_id") REFERENCES "folders"("f_id");



